services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always

  s3:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./s3:/data
      - ./letsencrypt/live/rexmit.balasolu.com/:/root/.minio/certs
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  rexmit:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: rexmit.Dockerfile
      target: final-rexmit
    ports:
      - 5000:5000
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
      - DISCORD_CLIENTID=${DISCORD_CLIENTID}
      - DISCORD_CLIENTSECRET=${DISCORD_CLIENTSECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GPT_SECRET=${GPT_SECRET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_ACCESS_KEY_SECRET=${S3_ACCESS_KEY_SECRET}
      - S3_ENDPOINT=${S3_ENDPOINT}
    restart: always

  nginx:
    depends_on:
      - rexmit
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    restart: always