version: "3.9"

services:

    rexmit-serenity:
        build:
            context: .
            dockerfile: etc/docker/rexmit-debug.Dockerfile
            target: serenity-prod
        secrets:
            - discord-token
        environment:
            - APPLICATION__DISCORDOPTIONS__TOKEN=/run/secrets/discord-token
        ports:
            - 5002:5002
        restart: always

secrets:

    discord-token:
        file: secrets/discord-token
